# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 557ad8e4cde25dbcbdbc53893cd999fe202d8d55d7c1cbb020358e2989bbbe249d470d74cd8cad9f1caf26b3c888eba7816c4b011270c955b4e9d91720c46b2e
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  facebook_callback_url: "http://localhost:3000/oauth/callback?provider=facebook"
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secrets_key: <%= ENV["TWITTER_SECRETS_KEY"] %>
  twitter_callback_url: "http://127.0.0.1:3000/oauth/callback?provider=twitter"
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_fog_directory: <%= ENV["AWS_FOG_DIRECTORY"] %>

test:
  secret_key_base: a3109bf702bd025f075af9e237b6a88282e8aff1bd6fd0a63970ab1a8240dcce0f32cbbf056ed32f99d1604db65b8971553549ead77b4b5195f9bbdef107ed96
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  facebook_callback_url: "http://localhost:3000/oauth/callback?provider=facebook"
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secrets_key: <%= ENV["TWITTER_SECRETS_KEY"] %>
  twitter_callback_url: "http://127.0.0.1:3000/oauth/callback?provider=twitter"


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  facebook.callback_url: <%= ENV["FACEBOOK_CALLBACK_URL"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secrets_key: <%= ENV["TWITTER_SECRETS_KEY"] %>
  twitter_callback_url: <%= ENV["TWITTER_CALLBACK_URL"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_fog_directory: <%= ENV["AWS_FOG_DIRECTORY"] %>
  facebook_callback_url: <%= ENV["SORCERY_FACEBOOK_CALLBACK_URL"] %>
  twitter_callback_url: <%= ENV["SORCERY_TWITTER_CALLBACK_URL"] %>
